export const CATEGORIES = Object.freeze([
  { id: 'shawarma', label: 'Шаурма', icon: 'wrap' },
  { id: 'doner', label: 'Донеры', icon: 'doner' },
  { id: 'burgers', label: 'Бургеры', icon: 'burger' },
  { id: 'hotdogs', label: 'Хот-доги', icon: 'hotdog' },
  { id: 'snacks', label: 'Закуски', icon: 'fries' },
]);

export const PRODUCTS = Object.freeze([
  {
    id: 'classic-shawarma',
    category: 'shawarma',
    name: 'Классическая шаурма',
    description: 'Курица или говядина, лаваш, салат, огурец, томат и фирменный соус',
    price: 300,
    pricePrefix: 'от',
    badge: 'Хит',
    image: 'assets/catalog/classic-shawarma.webp',
    icon: 'wrap',
    configurable: true,
  },
  {
    id: 'tasty-shawarma',
    category: 'shawarma',
    name: 'Тейсти-шава',
    description: 'Мясо, лаваш, салат, огурец, томат и соус «Гриль»',
    price: 350,
    pricePrefix: 'от',
    badge: null,
    image: 'assets/catalog/classic-shawarma.webp',
    icon: 'wrap',
    configurable: true,
  },
  {
    id: 'curry-shawarma',
    category: 'shawarma',
    name: 'Карри',
    description: 'Мясо, лаваш, салат, огурец, томат и соус «Карри»',
    price: 350,
    pricePrefix: 'от',
    badge: null,
    image: 'assets/catalog/classic-shawarma.webp',
    icon: 'wrap',
    configurable: true,
  },
  {
    id: 'burger-shawarma',
    category: 'shawarma',
    name: 'Бургерная',
    description: 'Мясо, лаваш, салат, огурец, томат и соус «Бургер»',
    price: 350,
    pricePrefix: 'от',
    badge: null,
    image: 'assets/catalog/classic-shawarma.webp',
    icon: 'wrap',
    configurable: true,
  },
  {
    id: 'bbq-shawarma',
    category: 'shawarma',
    name: 'Барбекю',
    description: 'Мясо, лаваш, салат, огурец, томат и соус BBQ',
    price: 350,
    pricePrefix: 'от',
    badge: null,
    image: 'assets/catalog/classic-shawarma.webp',
    icon: 'wrap',
    configurable: true,
  },
  {
    id: 'truffle-shawarma',
    category: 'shawarma',
    name: 'Трюфельная',
    description: 'Мясо, лаваш, салат, огурец, томат и трюфельный соус',
    price: 380,
    pricePrefix: 'от',
    badge: null,
    image: 'assets/catalog/classic-shawarma.webp',
    icon: 'wrap',
    configurable: true,
  },
  {
    id: 'four-cheese-shawarma',
    category: 'shawarma',
    name: '4 сыра',
    description: 'Мясо, сырный салат, огурец, томат, Блю-чиз, Моцарелла и Чеддер',
    price: 430,
    pricePrefix: 'от',
    badge: null,
    image: 'assets/catalog/classic-shawarma.webp',
    icon: 'wrap',
    configurable: true,
  },
  {
    id: 'doner',
    category: 'doner',
    name: 'Донер',
    description: 'Курица или говядина, турецкая пита, огурец, томат и фирменный соус',
    price: 350,
    pricePrefix: 'от',
    badge: null,
    image: 'assets/catalog/doner.webp',
    icon: 'doner',
    configurable: true,
  },
  {
    id: 'doner-box',
    category: 'doner',
    name: 'Донер-BOX',
    description: 'Мясо, лаваш, огурец, томат, картофель фри и фирменный соус',
    price: 550,
    pricePrefix: 'от',
    badge: null,
    image: 'assets/catalog/doner-box.webp',
    icon: 'doner',
    configurable: true,
  },
  {
    id: 'burger-standard',
    category: 'burgers',
    name: 'Бургер Стандарт',
    description: 'Булочка, котлета, сыр, свежие овощи и фирменный соус',
    price: 350,
    pricePrefix: '',
    badge: null,
    image: 'assets/catalog/burger-standard.webp',
    icon: 'burger',
    configurable: false,
  },
  {
    id: 'burger-double',
    category: 'burgers',
    name: 'Бургер Двойной',
    description: 'Булочка, две котлеты, сыр, свежие овощи и фирменный соус',
    price: 500,
    pricePrefix: '',
    badge: null,
    image: 'assets/catalog/burger-double.webp',
    icon: 'burger',
    configurable: false,
  },
  {
    id: 'hotdog-danish',
    category: 'hotdogs',
    name: 'Хот-дог Датский',
    description: 'Булочка, куриная сосиска, солёный огурец, лук фри, кетчуп и майонез',
    price: 250,
    pricePrefix: '',
    badge: null,
    image: 'assets/catalog/hotdog-danish.webp',
    icon: 'hotdog',
    configurable: false,
  },
  {
    id: 'squid-rings',
    category: 'snacks',
    name: 'Кольца кальмара',
    description: 'В панировке, 7 шт.',
    price: 350,
    pricePrefix: '',
    badge: null,
    image: 'assets/catalog/squid-rings.webp',
    icon: 'rings',
    configurable: false,
  },
  {
    id: 'nuggets',
    category: 'snacks',
    name: 'Наггетсы',
    description: 'Куриные, 6 шт.',
    price: 200,
    pricePrefix: '',
    badge: null,
    image: 'assets/catalog/nuggets.webp',
    icon: 'bites',
    configurable: false,
  },
  {
    id: 'breaded-shrimps',
    category: 'snacks',
    name: 'Креветки в панировке',
    description: 'Хрустящие, 6 шт.',
    price: 450,
    pricePrefix: '',
    badge: null,
    image: 'assets/catalog/breaded-shrimps.webp',
    icon: 'shrimp',
    configurable: false,
  },
  {
    id: 'cheese-sticks',
    category: 'snacks',
    name: 'Сырные палочки',
    description: 'В хрустящей панировке, 5 шт.',
    price: 250,
    pricePrefix: '',
    badge: null,
    image: 'assets/catalog/cheese-sticks.webp',
    icon: 'cheese',
    configurable: false,
  },
  {
    id: 'fries',
    category: 'snacks',
    name: 'Картофель фри',
    description: 'Хрустящий картофель, 200 г',
    price: 200,
    pricePrefix: '',
    badge: null,
    image: 'assets/catalog/fries.webp',
    icon: 'fries',
    configurable: false,
  },
  {
    id: 'country-potatoes',
    category: 'snacks',
    name: 'Картофель по-деревенски',
    description: 'Золотистые дольки, 200 г',
    price: 200,
    pricePrefix: '',
    badge: null,
    image: 'assets/catalog/country-potatoes.webp',
    icon: 'potato',
    configurable: false,
  },
]);
